# Difference between List and Numpy Array 

In [11]:
import numpy as np
L=[1,2,3]
A=np.array([1,2,3])

## Looping through List 

In [12]:
for e in L:
    print(e)

1
2
3


## Looping through Array

In [13]:
for e in A:
    print(e)

1
2
3


## Addition operation on a list & Array 

In [14]:
L.append(4)
L

[1, 2, 3, 4]

In [15]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

Append is not possible on an array

In [16]:
L=L+[5]
L

[1, 2, 3, 4, 5]

In [17]:
A=A+[4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Addition is not possible on an Array

In [19]:
L2=[]
for e in L:
    L2.append(e+e)
L2

[2, 4, 6, 8, 10]

In [21]:
A+A

array([2, 4, 6])

Plus sign with list does concatenation and Plus sign with Arrays does vector addition.In numpy mos operations act element wise.

Square root calculations using numpy 

In [22]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

Logrithm using numpy 

In [24]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

Exponential function using Numpy 

In [25]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

If we want to perform Square,Logrithm and Exponential functions in List then we have to do on individual elelemts using loo.This takes more time and more lines of code.